# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createwindow_ui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_createWindow(object):
    def setupUi(self, createWindow):
        createWindow.setObjectName("createWindow")
        createWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        createWindow.resize(666, 572)
        createWindow.setMinimumSize(QtCore.QSize(666, 572))
        createWindow.setMaximumSize(QtCore.QSize(666, 572))
        self.groupBox = QtWidgets.QGroupBox(createWindow)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 640, 60))
        self.groupBox.setStyleSheet("color:#505050;")
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 20, 620, 40))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pathText = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.pathText.setReadOnly(True)
        self.pathText.setObjectName("pathText")
        self.gridLayout.addWidget(self.pathText, 0, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.openPath = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.openPath.setAutoRaise(False)
        self.openPath.setArrowType(QtCore.Qt.NoArrow)
        self.openPath.setObjectName("openPath")
        self.gridLayout.addWidget(self.openPath, 0, 2, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(createWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 80, 646, 354))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_5.setContentsMargins(6, -1, -1, -1)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(69, 25))
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.imageList = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.imageList.setMinimumSize(QtCore.QSize(640, 310))
        self.imageList.setMaximumSize(QtCore.QSize(640, 310))
        self.imageList.setToolTip("")
        self.imageList.setToolTipDuration(5)
        self.imageList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.imageList.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.imageList.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.imageList.setAlternatingRowColors(False)
        self.imageList.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.imageList.setIconSize(QtCore.QSize(86, 86))
        self.imageList.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.imageList.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.imageList.setMovement(QtWidgets.QListView.Snap)
        self.imageList.setFlow(QtWidgets.QListView.LeftToRight)
        self.imageList.setProperty("isWrapping", True)
        self.imageList.setGridSize(QtCore.QSize(150, 150))
        self.imageList.setViewMode(QtWidgets.QListView.IconMode)
        self.imageList.setUniformItemSizes(False)
        self.imageList.setWordWrap(False)
        self.imageList.setObjectName("imageList")
        self.verticalLayout_4.addWidget(self.imageList)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.frame = QtWidgets.QFrame(createWindow)
        self.frame.setGeometry(QtCore.QRect(10, 439, 641, 71))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 380, 77))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.createName = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.createName.setObjectName("createName")
        self.gridLayout_2.addWidget(self.createName, 0, 1, 1, 1)
        self.createDesc = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.createDesc.setObjectName("createDesc")
        self.gridLayout_2.addWidget(self.createDesc, 1, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_35.setObjectName("label_35")
        self.gridLayout_2.addWidget(self.label_35, 0, 0, 1, 1)
        self.label_dsad = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_dsad.setObjectName("label_dsad")
        self.gridLayout_2.addWidget(self.label_dsad, 1, 0, 1, 1)
        self.box = QtWidgets.QTextBrowser(self.frame)
        self.box.setEnabled(True)
        self.box.setGeometry(QtCore.QRect(390, 4, 251, 55))
        self.box.setMinimumSize(QtCore.QSize(251, 55))
        self.box.setMaximumSize(QtCore.QSize(251, 55))
        self.box.setAutoFillBackground(False)
        self.box.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"\n"
"p span{\n"
"margin:auto !important;\n"
"text-align:center;\n"
"font-size:14px;\n"
"color:red;\n"
"}")
        self.box.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.box.setAutoFormatting(QtWidgets.QTextEdit.AutoNone)
        self.box.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.box.setObjectName("box")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(390, 3, 201, 60))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loadingGif = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.loadingGif.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.loadingGif.setObjectName("loadingGif")
        self.horizontalLayout.addWidget(self.loadingGif)
        self.loadingText = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.loadingText.setStyleSheet("font-size:14pt; color:#505050;")
        self.loadingText.setObjectName("loadingText")
        self.horizontalLayout.addWidget(self.loadingText)
        self.errorInfo = QtWidgets.QLabel(self.frame)
        self.errorInfo.setGeometry(QtCore.QRect(390, 10, 241, 51))
        self.errorInfo.setStyleSheet("font-size:14px;\n"
"color:red;\n"
"")
        self.errorInfo.setText("")
        self.errorInfo.setWordWrap(True)
        self.errorInfo.setObjectName("errorInfo")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(createWindow)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(410, 500, 250, 70))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.createButton = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.createButton.setAutoDefault(False)
        self.createButton.setDefault(True)
        self.createButton.setObjectName("createButton")
        self.gridLayout_3.addWidget(self.createButton, 0, 1, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout_3.addWidget(self.cancelButton, 0, 0, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(createWindow)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 520, 433, 26))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.keepRaw = QtWidgets.QCheckBox(self.gridLayoutWidget_4)
        self.keepRaw.setToolTipDuration(-1)
        self.keepRaw.setStyleSheet("font-size:11pt; color:#505050;")
        self.keepRaw.setObjectName("keepRaw")
        self.gridLayout_4.addWidget(self.keepRaw, 0, 0, 1, 1)

        self.retranslateUi(createWindow)
        QtCore.QMetaObject.connectSlotsByName(createWindow)

    def retranslateUi(self, createWindow):
        _translate = QtCore.QCoreApplication.translate
        createWindow.setWindowTitle(_translate("createWindow", "Create Session"))
        self.groupBox.setTitle(_translate("createWindow", "Images Location"))
        self.pushButton.setText(_translate("createWindow", "Auto Detect"))
        self.label.setText(_translate("createWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#505050;\">Path:</span></p></body></html>"))
        self.openPath.setText(_translate("createWindow", "..."))
        self.label_2.setText(_translate("createWindow", "<html><head/><body><p><span style=\" font-size:16pt; color:#505050;\">Images</span></p></body></html>"))
        self.label_35.setText(_translate("createWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#505050;\">Name:</span></p></body></html>"))
        self.label_dsad.setText(_translate("createWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#505050;\">Description:</span></p></body></html>"))
        self.box.setHtml(_translate("createWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.loadingGif.setText(_translate("createWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.loadingText.setText(_translate("createWindow", "<html><head/><body><p><span style=\" font-size:14pt; color:#505050;\">Processing...</span></p></body></html>"))
        self.createButton.setText(_translate("createWindow", "Create"))
        self.cancelButton.setText(_translate("createWindow", "Cancel"))
        self.keepRaw.setToolTip(_translate("createWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Saves the RAW images (without deleting them from a memory card) to the session file. Allows you to export them later if needed.</span></p></body></html>"))
        self.keepRaw.setText(_translate("createWindow", "Keep RAW"))

