# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow_ui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(700, 700))
        MainWindow.setMaximumSize(QtCore.QSize(700, 700))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalWidget.setGeometry(QtCore.QRect(0, 0, 160, 700))
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, 10, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.sessionList = QtWidgets.QListWidget(self.verticalWidget)
        self.sessionList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.sessionList.setObjectName("sessionList")
        self.verticalLayout.addWidget(self.sessionList)
        self.formWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.formWidget_2.setGeometry(QtCore.QRect(160, 640, 220, 60))
        self.formWidget_2.setObjectName("formWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formWidget_2)
        self.formLayout_2.setContentsMargins(6, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.formWidget_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.comboBox = QtWidgets.QComboBox(self.formWidget_2)
        self.comboBox.setObjectName("comboBox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.sesFilter = QtWidgets.QLineEdit(self.formWidget_2)
        self.sesFilter.setMaximumSize(QtCore.QSize(180, 16777215))
        self.sesFilter.setStyleSheet("")
        self.sesFilter.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.sesFilter.setClearButtonEnabled(False)
        self.sesFilter.setObjectName("sesFilter")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sesFilter)
        self.label_2 = QtWidgets.QLabel(self.formWidget_2)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(350, 70, 301, 271))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 50, 301, 221))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setMidLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 1, 280, 220))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.date_text = QtWidgets.QLabel(self.gridLayoutWidget)
        self.date_text.setStyleSheet("font-size:11pt; color:#505050;")
        self.date_text.setObjectName("date_text")
        self.gridLayout.addWidget(self.date_text, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.desc_Box = QtWidgets.QTextBrowser(self.gridLayoutWidget)
        self.desc_Box.setMinimumSize(QtCore.QSize(200, 150))
        self.desc_Box.setMaximumSize(QtCore.QSize(200, 150))
        self.desc_Box.setStyleSheet("background-color:rgba(0,0,0,0);font-size:12pt; color:#505050;")
        self.desc_Box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.desc_Box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.desc_Box.setObjectName("desc_Box")
        self.gridLayout.addWidget(self.desc_Box, 2, 0, 1, 1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 301, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sesName = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.sesName.setStyleSheet("font-size:18pt; color:#505050;")
        self.sesName.setWordWrap(True)
        self.sesName.setObjectName("sesName")
        self.horizontalLayout_2.addWidget(self.sesName, 0, QtCore.Qt.AlignHCenter)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(440, 660, 251, 51))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(12)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.createSesButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.createSesButton.setMaximumSize(QtCore.QSize(130, 23))
        self.createSesButton.setObjectName("createSesButton")
        self.gridLayout_2.addWidget(self.createSesButton, 0, 0, 1, 1)
        self.manageButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.manageButton.setEnabled(False)
        self.manageButton.setMaximumSize(QtCore.QSize(130, 23))
        self.manageButton.setObjectName("manageButton")
        self.gridLayout_2.addWidget(self.manageButton, 0, 1, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(420, 350, 260, 51))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_5.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setHorizontalSpacing(12)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.sesDelete = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.sesDelete.setEnabled(True)
        self.sesDelete.setMinimumSize(QtCore.QSize(130, 23))
        self.sesDelete.setMaximumSize(QtCore.QSize(130, 23))
        self.sesDelete.setInputMethodHints(QtCore.Qt.ImhNone)
        self.sesDelete.setDefault(False)
        self.sesDelete.setFlat(False)
        self.sesDelete.setObjectName("sesDelete")
        self.gridLayout_5.addWidget(self.sesDelete, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Session Manager"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; color:#505050;\">Sessions</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; color:#505050;\">Sort:</span></p></body></html>"))
        self.sesFilter.setPlaceholderText(_translate("MainWindow", "Search"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; color:#505050;\">Search:</span></p></body></html>"))
        self.date_text.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#505050;\"></span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#505050;\">Description:</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#505050;\">Creation Date:</span></p></body></html>"))
        self.desc_Box.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.sesName.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; color:#505050;\">Select a session</span></p></body></html>"))
        self.createSesButton.setText(_translate("MainWindow", "Create Session"))
        self.manageButton.setText(_translate("MainWindow", "Open Session"))
        self.sesDelete.setText(_translate("MainWindow", "Delete Session"))

