# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'managewindow_ui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet("#contents{\n"
"background:rgba(0,0,0,0);\n"
"}")
        self.contents = QtWidgets.QFrame(MainWindow)
        self.contents.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.contents.setStyleSheet("")
        self.contents.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contents.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contents.setObjectName("contents")
        self.stackedWidget = QtWidgets.QStackedWidget(self.contents)
        self.stackedWidget.setGeometry(QtCore.QRect(211, 50, 589, 550))
        self.stackedWidget.setObjectName("stackedWidget")
        self.proofs = QtWidgets.QWidget()
        self.proofs.setObjectName("proofs")
        self.proof_list = QtWidgets.QListWidget(self.proofs)
        self.proof_list.setGeometry(QtCore.QRect(0, 40, 589, 330))
        self.proof_list.setObjectName("proof_list")
        self.title = QtWidgets.QLabel(self.proofs)
        self.title.setGeometry(QtCore.QRect(0, 0, 591, 41))
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.create_button = QtWidgets.QPushButton(self.proofs)
        self.create_button.setGeometry(QtCore.QRect(450, 500, 100, 32))
        self.create_button.setMinimumSize(QtCore.QSize(100, 32))
        self.create_button.setMaximumSize(QtCore.QSize(100, 32))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.create_button.setFont(font)
        self.create_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.create_button.setDefault(False)
        self.create_button.setFlat(False)
        self.create_button.setObjectName("create_button")
        self.shift_proof = QtWidgets.QWidget(self.proofs)
        self.shift_proof.setGeometry(QtCore.QRect(520, 344, 68, 25))
        self.shift_proof.setObjectName("shift_proof")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.shift_proof)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.remove_proof = QtWidgets.QPushButton(self.shift_proof)
        self.remove_proof.setMinimumSize(QtCore.QSize(20, 23))
        self.remove_proof.setMaximumSize(QtCore.QSize(20, 23))
        self.remove_proof.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.remove_proof.setFlat(True)
        self.remove_proof.setObjectName("remove_proof")
        self.horizontalLayout_2.addWidget(self.remove_proof)
        self.add_proof = QtWidgets.QPushButton(self.shift_proof)
        self.add_proof.setMinimumSize(QtCore.QSize(20, 23))
        self.add_proof.setMaximumSize(QtCore.QSize(20, 23))
        self.add_proof.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_proof.setFlat(True)
        self.add_proof.setObjectName("add_proof")
        self.horizontalLayout_2.addWidget(self.add_proof)
        self.proof_info = QtWidgets.QWidget(self.proofs)
        self.proof_info.setGeometry(QtCore.QRect(0, 370, 212, 75))
        self.proof_info.setObjectName("proof_info")
        self.formLayout_2 = QtWidgets.QFormLayout(self.proof_info)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_2.setContentsMargins(6, 6, 6, 6)
        self.formLayout_2.setSpacing(6)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.proof_info)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.search_filter = QtWidgets.QLineEdit(self.proof_info)
        self.search_filter.setMinimumSize(QtCore.QSize(0, 0))
        self.search_filter.setText("")
        self.search_filter.setObjectName("search_filter")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.search_filter)
        self.label_4 = QtWidgets.QLabel(self.proof_info)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_9 = QtWidgets.QLabel(self.proof_info)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_9)
        self.label_6 = QtWidgets.QLabel(self.proof_info)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_10 = QtWidgets.QLabel(self.proof_info)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_10)
        self.progress = QtWidgets.QProgressBar(self.proofs)
        self.progress.setGeometry(QtCore.QRect(260, 390, 251, 23))
        self.progress.setProperty("value", 0)
        self.progress.setObjectName("progress")
        self.stackedWidget.addWidget(self.proofs)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget.addWidget(self.page_3)
        self.info_frame = QtWidgets.QFrame(self.contents)
        self.info_frame.setGeometry(QtCore.QRect(0, 50, 211, 550))
        self.info_frame.setStyleSheet("")
        self.info_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.info_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.info_frame.setObjectName("info_frame")
        self.details = QtWidgets.QGroupBox(self.info_frame)
        self.details.setGeometry(QtCore.QRect(10, 10, 201, 271))
        self.details.setFlat(False)
        self.details.setObjectName("details")
        self.info_misc = QtWidgets.QGroupBox(self.details)
        self.info_misc.setGeometry(QtCore.QRect(0, 60, 268, 191))
        self.info_misc.setMinimumSize(QtCore.QSize(191, 111))
        self.info_misc.setFlat(False)
        self.info_misc.setObjectName("info_misc")
        self.layoutWidget = QtWidgets.QWidget(self.info_misc)
        self.layoutWidget.setGeometry(QtCore.QRect(2, 30, 181, 171))
        self.layoutWidget.setObjectName("layoutWidget")
        self._2 = QtWidgets.QFormLayout(self.layoutWidget)
        self._2.setContentsMargins(0, 0, 0, 0)
        self._2.setObjectName("_2")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self._2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.image_count = QtWidgets.QLabel(self.layoutWidget)
        self.image_count.setText("")
        self.image_count.setAlignment(QtCore.Qt.AlignCenter)
        self.image_count.setObjectName("image_count")
        self._2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.image_count)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setObjectName("label_12")
        self._2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.create_date = QtWidgets.QLabel(self.layoutWidget)
        self.create_date.setText("")
        self.create_date.setAlignment(QtCore.Qt.AlignCenter)
        self.create_date.setObjectName("create_date")
        self._2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.create_date)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        self.label_13.setObjectName("label_13")
        self._2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.has_raw = QtWidgets.QLabel(self.layoutWidget)
        self.has_raw.setText("")
        self.has_raw.setAlignment(QtCore.Qt.AlignCenter)
        self.has_raw.setObjectName("has_raw")
        self._2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.has_raw)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setObjectName("label_14")
        self._2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.modify_date = QtWidgets.QLabel(self.layoutWidget)
        self.modify_date.setText("")
        self.modify_date.setAlignment(QtCore.Qt.AlignCenter)
        self.modify_date.setObjectName("modify_date")
        self._2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.modify_date)
        self.selection = QtWidgets.QWidget(self.info_frame)
        self.selection.setGeometry(QtCore.QRect(0, 350, 213, 90))
        self.selection.setObjectName("selection")
        self.selection_layout = QtWidgets.QVBoxLayout(self.selection)
        self.selection_layout.setContentsMargins(0, 0, 0, 0)
        self.selection_layout.setSpacing(0)
        self.selection_layout.setObjectName("selection_layout")
        self.photo_select = QtWidgets.QPushButton(self.selection)
        self.photo_select.setMinimumSize(QtCore.QSize(211, 30))
        self.photo_select.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.photo_select.setCheckable(True)
        self.photo_select.setChecked(True)
        self.photo_select.setFlat(True)
        self.photo_select.setObjectName("photo_select")
        self.selection_layout.addWidget(self.photo_select)
        self.proof_select = QtWidgets.QPushButton(self.selection)
        self.proof_select.setMinimumSize(QtCore.QSize(211, 30))
        self.proof_select.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.proof_select.setCheckable(True)
        self.proof_select.setChecked(False)
        self.proof_select.setFlat(True)
        self.proof_select.setObjectName("proof_select")
        self.selection_layout.addWidget(self.proof_select)
        self.final_select = QtWidgets.QPushButton(self.selection)
        self.final_select.setMinimumSize(QtCore.QSize(211, 30))
        self.final_select.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.final_select.setCheckable(True)
        self.final_select.setFlat(True)
        self.final_select.setObjectName("final_select")
        self.selection_layout.addWidget(self.final_select)
        self.navBar_create = QtWidgets.QFrame(self.contents)
        self.navBar_create.setGeometry(QtCore.QRect(0, 0, 809, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.navBar_create.sizePolicy().hasHeightForWidth())
        self.navBar_create.setSizePolicy(sizePolicy)
        self.navBar_create.setMinimumSize(QtCore.QSize(809, 50))
        self.navBar_create.setMaximumSize(QtCore.QSize(809, 50))
        self.navBar_create.setStyleSheet("")
        self.navBar_create.setObjectName("navBar_create")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.navBar_create)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.home_button = QtWidgets.QPushButton(self.navBar_create)
        self.home_button.setMaximumSize(QtCore.QSize(70, 16777215))
        self.home_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.home_button.setFlat(True)
        self.home_button.setObjectName("home_button")
        self.horizontalLayout_5.addWidget(self.home_button)
        self.navSep_create = QtWidgets.QFrame(self.navBar_create)
        self.navSep_create.setStyleSheet("")
        self.navSep_create.setFrameShadow(QtWidgets.QFrame.Plain)
        self.navSep_create.setFrameShape(QtWidgets.QFrame.VLine)
        self.navSep_create.setObjectName("navSep_create")
        self.horizontalLayout_5.addWidget(self.navSep_create)
        self.session_name = QtWidgets.QLabel(self.navBar_create)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.session_name.setFont(font)
        self.session_name.setObjectName("session_name")
        self.horizontalLayout_5.addWidget(self.session_name)
        self.gridLayout_8.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Form"))
        self.title.setText(_translate("MainWindow", "Photos"))
        self.create_button.setText(_translate("MainWindow", "Edit"))
        self.remove_proof.setText(_translate("MainWindow", "-"))
        self.add_proof.setText(_translate("MainWindow", "+"))
        self.label_3.setText(_translate("MainWindow", "Name:"))
        self.label_4.setText(_translate("MainWindow", "File Name:"))
        self.label_6.setText(_translate("MainWindow", "Opened:"))
        self.progress.setFormat(_translate("MainWindow", "Generating Thumbnails... %p%"))
        self.details.setTitle(_translate("MainWindow", "MANAGE"))
        self.info_misc.setTitle(_translate("MainWindow", "Information"))
        self.label_11.setText(_translate("MainWindow", "Images:"))
        self.label_12.setText(_translate("MainWindow", "Creation Date:"))
        self.label_13.setText(_translate("MainWindow", "Raw Saved:"))
        self.label_14.setText(_translate("MainWindow", "Last Modified:"))
        self.photo_select.setText(_translate("MainWindow", "Photos"))
        self.proof_select.setText(_translate("MainWindow", "Proofs"))
        self.final_select.setText(_translate("MainWindow", "Finals"))
        self.navBar_create.setAccessibleName(_translate("MainWindow", "navBar"))
        self.home_button.setText(_translate("MainWindow", "Home"))
        self.session_name.setText(_translate("MainWindow", "Session Name"))

